//domain
http://localhost:4000

#this headers will sended to every request
Content-Type: application/json
Authorization: Bearer [your access token]
--
--
POST /api/auth/signup 
{
"name":"Person One",
"email":"Person1@gmail.com",
"password":"Person1@123",
"birthday":"11/03/2003",
"gender":"male"
}
--
POST /api/auth/signin 
{
"email":"mdmuttaqin20@gmail.com",
"password":"Muttaqin@123"
}

--
DELETE /api/auth/signout

--
PUT /api/auth/token-refresh 

--
POST /api/auth/verify/cb7837e0b9c411ad21913542767b700c574316dd6229869d8a

--
POST /api/auth/resend-token
{
  "email":"mdmuttaqin20@gmail.com"
}
--
POST /api/auth/password/forgot-password
{
"email":"mdmuttaqin20@gmail.com"
}
--
POST /api/auth/2fa/verify/venuegbugbgb
{
  "otp":"fneiff"
}
--
POST /api/auth/password/reset/djfneifnen 
{
 "password":"Muttaqin@456"
}

--
POST /api/auth/password 
{
  "oldPassword":"Muttaqin@123",
  "newPassword":"Muttaqin@456"
}
